### ISSUE TITLE
AEM Forms demo machine fails to properly setup CM functionality

### ISSUE THREAD

**Issue by ridmaur** [Adobe-Marketing-Cloud/aem-demo-machine#13]
I tried now three times, but when installing a new demo machine (6.1) with Forms packages installed it won't properly show the Correspondence Management UI: e.g. Letters, Document Fragments and Data Dictionaries.

**Comment by coatpont** [comment]
hey Rob, I tried the same (running the "Add-ons/Forms/Download Packages" option first, to make sure the latest packages are loaded for Forms), and apparently the setup process is working ok (all packages are loaded up ok, including for demo sites) but I'm not skilled enough with AEM Forms to comment on what's broken in the Correspondence Management UI. I wonder if the latest versions have a dependency on AEM 6.1 SP1 maybe. I suggest reaching out to Forms experts on symptoms so that we can find a resolution path. Alternatively, you might want to use the latest AEM 6.2 betas (Load19)

**Comment by dkparmar** [comment]
Can you please let me know from where I will get license-aem6.properties because this demomachine required a license file and I don't have adobe client access for downloading license file, early reply appreciated.

**Comment by coatpont** [comment]
License files are available to licensed customers (via the Adobe licensing portal) and to Adobe partners - if you are working for an Adobe partner, your Adobe representative should be able to equip you with the required license

**Comment by coatpont** [comment]
@ridmaur I checked the 6.2 versions of Forms addons and demos lately, do you mind retrying and open the issue again if needed?

**Comment by ridmaur** [comment]
I will try it again somewhere next week. Let you know the results.

Kind regards / Met vriendelijke groet,
Rob In der Maur | principal solution consultant | Adobe | +31 646 32 42 49 | @ridmaur
[RIdM-sfMO]
